name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyterlab=3.0.12
  - mlflow=2.8.1
  - numpy=1.22.4
  - pytest 7.0.0
  - hydra-core=1.3.2
  - matplotlib=3.6.2
  - pandas=1.2.3
  - git=2.30.2
  - pip=20.3.3
  - scipy=1.7.3
  - scikit-learn=1.0.2
  - pip:
      - wandb==0.13.9
      - databricks_cli==0.8.7