ame: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyterlab=3.0.12
  - mlflow=2.8.1
  - numpy=1.22.4
  - cookiecutter=1.7.2
  - hydra-core=1.0.6
  - matplotlib=3.6.2
  - pandas=1.2.3
  - git=2.30.2
  - pip=20.3.3
  - scipy=1.7.3
  - scikit-learn=1.0.2
  - pip:
      - wandb==0.13.9
      - databricks_cli==0.8.7
      - git+https://github.com/udacity/Project-Build-an-ML-Pipeline-Starter.git#egg=wandb-utils&subdirectory=components